#+TITLE: Emacs configuration
#+AUTHOR: Spencer K. Clark
#+OPTIONS: toc:nil num:nil

Here I am using org-mode to organize my configuration file for emacs [[https://www.youtube.com/watch?v%3DSzA2YODtgK4][as shown
by Harry Schwartz.]]  This allows for easy documentation and organization;
within org-mode I can fold the file easily into separate sections, which
makes it more readable.

Many of the default general settings were inspired [[https://github.com/darothen/dotfiles/blob/master/emacs/.emacs][by Daniel
Rothenberg's emacs configuration.]]  

* General settings
** Load packages when emacs is idiling, rather than at start-up
#+BEGIN_SRC emacs-lisp
    (use-package idle-require
        :ensure t

        :init
        (setq idle-require-delay 5)

        :config
        (idle-require-mode 1)
    )
#+END_SRC
** Use better-defaults
better-defaults adds some settings to improve on the defaults of emacs.  More
information can be found here: https://github.com/technomancy/better-defaults

#+BEGIN_SRC emacs-lisp
    (use-package better-defaults
        :ensure t
    )
#+END_SRC

** Set the default tab width to 4 spaces
This is standard for Python and looks nice in other contexts too.

#+BEGIN_SRC emacs-lisp
    (setq default-tab-width 4)
#+END_SRC

** Show in progress key bindings quickly
This lets you quickly see what keys you've typed for a keyboard shortcut.  
By default emacs uses one second; here we change it to 0.1 seconds.  
See here for more information:
http://pragmaticemacs.com/emacs/show-unfinished-keystrokes-early/

#+BEGIN_SRC emacs-lisp
    (setq echo-keystrokes 0.1)
#+END_SRC

** Don't show the startup screen
I typically don't have a need for the startup screen, so it makes sense to
disable it.  See here for more information:
https://stackoverflow.com/questions/744672/unable-to-hide-welcome-screen-in-emacs

#+BEGIN_SRC emacs-lisp
   (setq inhibit-startup-screen t)
#+END_SRC

** If lines are longer than the display width, wrap them
#+BEGIN_SRC emacs-lisp
    (setq line-move-visual t)
#+END_SRC

** Ignore case in all tab-completion contexts
This makes finding files and commands easier.  See here for more information:
https://emacs.stackexchange.com/questions/32407/tab-completion-in-minibuffer-case-insensitive

#+BEGIN_SRC emacs-lisp
    (setq completion-ignore-case t)
    (setq read-file-name-completion-ignore-case t)
    (setq read-buffer-completion-ignore-case t)
#+END_SRC

** Turn off the bell
The warning bell is not often that important and can just be annoying.

#+BEGIN_SRC emacs-lisp
    (setq ring-bell-function 'ignore)
#+END_SRC
** Automatically limit lines to 79 characters
This is nice, because it automatically keeps text within the default width of a
terminal window.  It also enforces PEP8 compliance on this front in Python.
#+BEGIN_SRC emacs-lisp
    (setq-default fill-column 79)
    (setq-default auto-fill-function 'do-auto-fill)
#+END_SRC
** Use spaces for tabs
#+BEGIN_SRC emacs-lisp
    (setq-default indent-tabs-mode nil)
#+END_SRC
** Use UTF-8 encoding for all files
This allows for the display of special characters directly within emacs.  See
here for more information:
https://www.masteringemacs.org/article/working-coding-systems-unicode-emacs
#+BEGIN_SRC emacs-lisp
    (prefer-coding-system 'utf-8)
    (set-default-coding-systems 'utf-8)
    (set-terminal-coding-system 'utf-8)
    (set-keyboard-coding-system 'utf-8)
#+END_SRC
** Turn on syntax highlighting in all buffers
#+BEGIN_SRC emacs-lisp
    (global-font-lock-mode t)
#+END_SRC
** Require a newline at the end of all files
It is often recommmended to do this for all text files.  See here for more
information:
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
#+BEGIN_SRC emacs-lisp
    (setq require-final-newline t)
#+END_SRC
** Use which-key to enable searching key bindings
#+BEGIN_SRC emacs-lisp
    (use-package which-key
        :ensure t

        :config
        (which-key-mode)
    )
#+END_SRC
** Make flycheck errors more visible
#+BEGIN_SRC emacs-lisp
    (setq flycheck-highlighting-mode 'lines)
#+END_SRC
** Activate swiper
For nicer searching in files.
#+BEGIN_SRC emacs-lisp
     (use-package swiper
         :ensure t
     )

     (use-package ivy
        :ensure t

        :config
        (ivy-mode 1)
        (global-set-key "\C-s" 'swiper)
    )
#+END_SRC
* Python settings
** Syntax and style checking
Turn on Python-related syntax and style checking.
#+BEGIN_SRC emacs-lisp
    (use-package flycheck
        :ensure t
        :init (global-flycheck-mode))
    (add-hook 'python-mode-hook 'anaconda-mode)
    (add-hook 'python-mode-hook 'flycheck-mode)
#+END_SRC
* LaTeX settings
The majority of these settings were inspired from a great Stack Exchange answer:
https://tex.stackexchange.com/questions/50827/a-simpletons-guide-to-tex-workflow-with-emacs

** Add syntax checking for LaTeX
#+BEGIN_SRC emacs-lisp
    (add-hook 'TeX-mode-hook 'flycheck-mode)
#+END_SRC
** Parse TeX files automatically
See here for more details for why this is recommended: 
https://www.gnu.org/software/auctex/manual/auctex/Parsing-Files.html
#+BEGIN_SRC emacs-lisp
    (setq TeX-parse-self t)
    (setq TeX-auto-save t)
#+END_SRC
** Tell AUCTeX to always query for the master file
See here for more details:
https://www.gnu.org/software/auctex/manual/auctex.html#index-TeX_002dmaster-2
#+BEGIN_SRC emacs-lisp
    (setq-default TeX-master nil)
#+END_SRC
** Always export to PDF
#+BEGIN_SRC emacs-lisp
    (setq TeX-PDF-mode t)
#+END_SRC
** Highlight misspelled words when writing LaTeX
#+BEGIN_SRC emacs-lisp
    (add-hook 'TeX-mode-hook 'flyspell-mode)
#+END_SRC
** Enable environment folding
Fold environments for easier navigation throughout the document
#+BEGIN_SRC emacs-lisp
    (add-hook 'TeX-mode-hook (lambda () (TeX-fold-mode 1)))
#+END_SRC
** Expand standard quotation marks to csquotes
See here for more information:
https://tex.stackexchange.com/questions/39285/whats-the-advantage-of-using-csquotes-over-using-an-editors-auto-replacement-f
#+BEGIN_SRC emacs-lisp
    (setq LaTeX-csquotes-close-quote "}"
          LaTeX-csquotes-open-quote "\\enquote{")
#+END_SRC
** Enable LaTeX-math-mode
This adds shortcuts for typing math symbols; see here for more information:
https://www.gnu.org/software/auctex/manual/auctex/Mathematics.html
#+BEGIN_SRC emacs-lisp
    (add-hook 'TeX-mode-hook 'LaTeX-math-mode)
#+END_SRC
** Automatically pair delimiters
Here when using ~AUCTeX~ we make sure to take advantage of the ~CDLaTex~ library,
which provides some helpful tools for automatically pairing delimiters:
https://github.com/cdominik/cdlatex. 
#+BEGIN_SRC emacs-lisp
    (add-hook 'LaTeX-mode-hook 'turn-on-cdlatex)
#+END_SRC
* Fortran settings
** Enable flycheck in f90-mode
#+BEGIN_SRC emacs-lisp
    (add-hook 'f90-mode-hook 'flycheck-mode)
#+END_SRC
* Emacs lisp settings
** Enable flycheck in emacs lisp mode
Helps catch initialization file errors before they cause problems
#+BEGIN_SRC emacs-lisp
    (add-hook 'emacs-lisp-mode-hook 'flycheck-mode)
#+END_SRC
